<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net8.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <OpenApiGenerateDocuments>false</OpenApiGenerateDocuments>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>$(AssemblyName)</Title>
    <Version>0.1.4-beta</Version>
    <Authors>tayvey</Authors>
    <Company />
    <Description>...</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/tayvey/tayvey.tools</RepositoryUrl>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
	
  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="EPPlus" Version="7.5.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="9.0.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Quartz.AspNetCore" Version="3.13.1" />
    <PackageReference Include="SoapCore" Version="1.1.0.51" />
    <PackageReference Include="SqlSugarCore" Version="5.1.4.172" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.24" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>
	
</Project>